name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '15 17 * * *'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test
        env:
          AST_CI: true
          AST_CRUNCHYROLL_PROXYSERVER: ${{secrets.AST_CRUNCHYROLL_PROXYSERVER}}
          AST_CRUNCHYROLL_USERNAME: ${{secrets.AST_CRUNCHYROLL_USERNAME}}
          AST_CRUNCHYROLL_PASSWORD: ${{secrets.AST_CRUNCHYROLL_PASSWORD}}
          AST_CRUNCHYROLLBETA_PROXYSERVER: ${{secrets.AST_CRUNCHYROLLBETA_PROXYSERVER}}
          AST_CRUNCHYROLLBETA_USERNAME: ${{secrets.AST_CRUNCHYROLLBETA_USERNAME}}
          AST_CRUNCHYROLLBETA_PASSWORD: ${{secrets.AST_CRUNCHYROLLBETA_PASSWORD}}
          AST_FUNIMATION_PROXYSERVER: ${{secrets.AST_FUNIMATION_PROXYSERVER}}
          AST_FUNIMATION_USERNAME: ${{secrets.AST_FUNIMATION_USERNAME}}
          AST_FUNIMATION_PASSWORD: ${{secrets.AST_FUNIMATION_PASSWORD}}
          AST_VRV_PROXYSERVER: ${{secrets.AST_VRV_PROXYSERVER}}
          AST_VRV_USERNAME: ${{secrets.AST_VRV_USERNAME}}
          AST_VRV_PASSWORD: ${{secrets.AST_VRV_PASSWORD}}