name: vrv
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '45 17 * * *'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run ci:vrv
        env:
          AST_CI: true
          AST_VRV_PROXYSERVER: ${{secrets.AST_VRV_PROXYSERVER}}
          AST_VRV_USERNAME: ${{secrets.AST_VRV_USERNAME}}
          AST_VRV_PASSWORD: ${{secrets.AST_VRV_PASSWORD}}
